# Generated by Django 4.2.16 on 2024-12-03 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_customuser_options_categorymodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='categoryName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.categorymodel'),
        ),
    ]
